apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: leapfrogai-api
  namespace: {{ .Release.Namespace }}
spec:
  network:
    expose:
      - service: api
        podLabels:
          app.kubernetes.io/name: api
        gateway: tenant
        host: {{ .Values.subdomain }}
        port: 8080
    allow:
      # Permit intra-namespace communication for job communications
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        remoteGenerated: IntraNamespace

      # Todo: wide open for hitting in-cluster or external postgres/s3
      - direction: Egress
        podLabels:
          app.kubernetes.io/name: api
        remoteGenerated: Anywhere