variables:
  leapfrog-ui:
    domain: https://ai.uds.dev
    model: llama-cpp-python-gpu
  llama-cpp-python:
    gpu_enabled: "true"
    requests_gpu: 1
    limits_gpu: 1
  whisper:
    gpu_enabled: "true"
    requests_gpu: 1
    limits_gpu: 1