name: deploy-test
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "CODEOWNERS"
      - ".gitignore"
      - "docs/**"
      - "bundles/gpu/**"
      - ".github/**"

concurrency:
  group: deploy-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-test:
    runs-on: ai-ubuntu-big-boy-8-core
     
    steps:
        - name: Checkout Repo
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

        - name: Install UDS-CLI
          run: |
            wget https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Linux_amd64
            chmod +x uds-cli_v0.9.2_Linux_amd64
            sudo mv uds-cli_v0.9.2_Linux_amd64 /usr/local/bin/uds

        - name: Create CPU Bundle
          run: |
            uds create ./bundles/cpu/ --confirm

        - name: Setup K3D
          run: |
            wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash
          
        - name: Create UDS Cluster
          run: |
            uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-istio-dev:0.14.1 --confirm

        - name: Deploy CPU Bundle
          run: |
            uds deploy ./bundles/cpu/uds-bundle-leapfrogai-*.tar.zst --confirm
